---
description: Computer Build Parts
output-file: computer_build.html
skip_exec: true
skip_showdoc: true
title: Computer Build

---



<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

## Parts

|Part|Spec|Amount|Power|
|---|---|---|---|
[x] Motherboard|ASUS Prime X670-P Wifi CSM AM5 ATX Motherboard | \$339.36 | 30-50W |
[x] CPU | AMD Ryzen 9 7900X 12 Core AM5 5.6GHz CPU Processor | \$599 | 170W
[ ] RAM | Kingston 64GB (2x32GB) KF560C36BBEAK2-64 Fury Beast RGB 6000MHz DDR5 RAM | \$309 | 10W
[ ] Memory | Crucial T705 1TB CT1000T705SSD5 PCIe 5.0 2280 M.2 NVMe SSD - with Heatsink | \$289 | 11.55W
[ ] Memory | Seagate Barracuda 1TB (2016) | - 
[ ] Cooler | Thermalright Phantom Spirit 120 SE ARGB CPU Cooler - >166mm | \$59
[x] Case | Thermaltake View 200 TG ARGB Mid Tower ATX Case | \$78.78
[x] GPU | RTX3090 | 350W
[ ] PSU | Thermaltake Toughpower GF A3 Snow 1050W Power Supply | \$219
[ ] Fans | 3x 120mm | \$35


## **1. Central Processing Unit (CPU)**
> The CPU is vital for data preprocessing, running ML algorithms, and managing overall system operations. For ML tasks, a CPU with high core count and strong multi-threading capabilities is essential.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **CPU**       | **AMD Ryzen 9 7950X** | 16 cores / 32 threads, 4.5 GHz base, 5.7 GHz boost, AM5 socket | ~1,050 |
|               | **AMD Ryzen 9 7900X** | 12 cores / 24 threads, 4.7 GHz base, 5.6 GHz boost, AM5 socket | ~750 |
|               | **AMD Ryzen 7 7700X** | 8 cores / 16 threads, 4.5 GHz base, 5.4 GHz boost, AM5 socket | ~525 |

**_Recommendation:_**  
The **AMD Ryzen 9 7950X** is highly recommended for ML development due to its high core and thread count, which enhances parallel processing capabilities essential for handling complex ML tasks and large datasets.

## **2. Graphics Processing Unit (GPU)**
> GPUs are the backbone of modern ML workloads, especially for deep learning tasks. NVIDIA GPUs are typically preferred due to their CUDA cores and extensive support in ML frameworks.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **GPU**       | **NVIDIA GeForce RTX 4090** | 24 GB GDDR6X, 16,384 CUDA cores, PCIe 4.0, excellent for large-scale ML models | ~2,400 |
|               | **NVIDIA GeForce RTX 4080** | 16 GB GDDR6X, 9,728 CUDA cores, PCIe 4.0, great performance for ML | ~1,800 |
|               | **NVIDIA RTX A6000** | 48 GB GDDR6, 10,752 CUDA cores, ECC memory, optimized for professional ML workloads | ~6,750 |
|               | **NVIDIA GeForce RTX 4070 Ti** | 12 GB GDDR6X, 7,680 CUDA cores, PCIe 4.0, balanced performance and cost | ~1,200 |

**_Recommendation:_**  
For the best ML performance, the **NVIDIA GeForce RTX 4090** is ideal due to its superior CUDA core count and large VRAM, enabling efficient training of complex models. If budget constraints exist, the **RTX 4080** or **RTX 4070 Ti** offer excellent performance at a more accessible price.

## **3. Motherboard**
> A compatible motherboard ensures seamless integration of all components, supports multiple GPUs, offers ample RAM slots, and provides reliable power delivery.

| **Component**   | **Recommendation**             | **Key Features** | **Price Range (AUD)** |
|-----------------|--------------------------------|-------------------|------------------------|
| **Motherboard** | **ASUS PRIME X670-P WIFI**     | AM5 socket, 1 x PCIe 4.0 x16 slots 1 x PCIe 4.0 x8, DDR5 support, WiFi 6E, robust VRMs | ~219.99 |
|                 | **MSI MPG X670E Carbon WiFi**  | AM5 socket, Triple PCIe 5.0 x16 slots, DDR5, WiFi 6E, high-quality VRMs | ~675 |
|                 | **Gigabyte X670E AORUS Elite** | AM5 socket, Triple PCIe 5.0 x16 slots, DDR5, advanced thermal design | ~600 |
|                 | **ASRock X670E Taichi**        | AM5 socket, Triple PCIe 5.0 x16 slots, DDR5, premium build quality | ~900 |
|                 | **ASUS TUF Gaming X670E-Plus** | AM5 socket, 1 x PCIe 5.0 x16 slots, 1 x PCIe 4.0 x4, DDR5, military-grade components | ~749 |
|                 | **ASUS ProArt X670E-Creatort** | AM5 socket, 2 x PCIe 5.0 x16 slots, 1 x PCIe 4.0 x2, DDR5 | ~768
|                 | **ASUS ROG Strix X670E Gaming**| AM5 socker, 1 x PCIe 5.0 x16 slots, 1 x PCIe 4.0 x4, DDR5 | ~639

**_Recommendation:_**  
The **ASUS PRIME X670-P WIFI** offers a balanced mix of features, including dual PCIe 5.0 x16 slots suitable for dual GPU setups, robust power delivery, and DDR5 memory support, making it an excellent choice for ML development.

## **4. Memory (RAM)**
> Ample and fast RAM is crucial for handling large datasets and ensuring smooth multitasking during model training and evaluation.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **RAM**       | **G.Skill Trident Z5 RGB DDR5 64GB (2x32GB) 6000MHz** | High-speed DDR5, RGB aesthetics, low latency | ~450 |
|               | **Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz** | Reliable performance, high speed | ~225 |
|               | **Kingston Fury Beast DDR5 128GB (4x32GB) 6000MHz** | Massive capacity for extensive datasets | ~900 |
|               | **Crucial Ballistix DDR5 32GB (2x16GB) 5600MHz** | Budget-friendly, decent performance | ~195 |

**_Recommendation:_**  
For most ML applications, **64 GB DDR5 RAM** (e.g., **G.Skill Trident Z5 RGB DDR5 64GB**) strikes a good balance between capacity and speed. However, for very large datasets or complex models, opting for **128 GB DDR5 RAM** (e.g., **Kingston Fury Beast DDR5 128GB**) is advisable.

## **5. Storage**
> Fast and ample storage ensures quick data access, efficient model saving/loading, and smooth system performance.

| **Component**         | **Recommendation**                          | **Key Features**                                             | **Price Range (AUD)** |
|-----------------------|---------------------------------------------|--------------------------------------------------------------|---------------------|
| **Primary Storage**   | **Samsung 980 PRO 1TB NVMe SSD**            | PCIe 4.0, high read/write speeds, reliable | ~150 |
| **Secondary Storage** | **WD Black SN850X 2TB NVMe SSD**            | PCIe 4.0, larger capacity for datasets | ~300 |
|                       | **Samsung 990 PRO 2TB NVMe SSD**            | Latest generation, PCIe 4.0, extremely fast | ~375 |
|                       | **Crucial P5 Plus 4TB NVMe SSD**            | PCIe 4.0, massive storage for extensive datasets | ~675 |
|                       | **Seagate FireCuda 530 1TB NVMe SSD**        | PCIe 4.0, excellent endurance and reliability | ~180 |
|                       | **Corsair MP600 Pro XT 2TB NVMe SSD**        | PCIe 4.0, robust thermal management | ~330 |

**_Recommendation:_**  
A combination of a **1 TB NVMe SSD** for the operating system and frequently accessed data (e.g., **Samsung 980 PRO 1TB**) and a **2 TB NVMe SSD** for larger datasets and model storage (e.g., **WD Black SN850X 2TB**) is ideal. For maximum storage needs, consider adding a **4 TB NVMe SSD**.

## **6. Power Supply Unit (PSU)**
> A reliable PSU ensures stable power delivery to all components, especially when running multiple GPUs.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **PSU**       | **EVGA SuperNOVA 1200 G6 1200W** | 80+ Gold, fully modular, high wattage for dual GPUs | ~450 |
|               | **Corsair RM1000x 1000W 80+ Gold** | Fully modular, reliable performance | ~270 |
|               | **Seasonic Focus GX-850 850W** | 80+ Gold, fully modular | ~195 |
|               | **Be Quiet! Straight Power 11 1000W** | 80+ Platinum, fully modular | ~300 |
|               | **Corsair HX1200i 1200W** | 80+ Platinum, high efficiency | ~450 |

**_Recommendation:_**  
For dual GPU configurations, a **1200W PSU** like the **EVGA SuperNOVA 1200 G6** or **Corsair HX1200i** is recommended to ensure ample power headroom and stability, especially under heavy loads.

## **7. Cooling Solutions**
> Effective cooling is essential to maintain optimal performance and prolong the lifespan of your components, particularly the CPU and GPUs.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **CPU Cooler** | **Corsair iCUE H150i Elite Capellix** | 360mm AIO, RGB lighting, high-performance cooling | ~300 |
|               | **Noctua NH-D15 chromax.Black** | Dual tower air cooler, extremely efficient and quiet | ~150 |
|               | **be quiet! Dark Rock Pro 4** | High-performance air cooling, near-silent operation | ~135 |
|               | **NZXT Kraken Z73 RGB** | 360mm AIO, customizable LCD display, premium cooling | ~375 |
|               | **Arctic Liquid Freezer II 360** | 360mm AIO, excellent cooling performance | ~225 |

**_Recommendation:_**  
For optimal CPU cooling, consider a **high-performance AIO liquid cooler** like the **Corsair iCUE H150i Elite Capellix** or a top-tier **air cooler** like the **Noctua NH-D15 chromax.Black**. These options ensure your CPU remains cool during intensive ML tasks.

## **8. Computer Case (Chassis)**
> A spacious and well-ventilated case ensures that all components, especially multiple GPUs, have adequate airflow and space.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **Case**      | **Fractal Design Meshify 2** | ATX, excellent airflow, spacious interior | ~225 |
|               | **Thermaltake Core P8** | ATX, open-frame design, maximum airflow | ~300 |
|               | **NZXT H710** | ATX, sleek design, good cable management | ~240 |
|               | **Lian Li PC-O11 Dynamic** | ATX, stylish with excellent cooling and showcase features | ~225 |
|               | **Phanteks Eclipse P600S** | ATX, hybrid cooling support, sound-dampening | ~300 |
|               | **Corsair Obsidian Series 750D** | ATX, large and versatile, robust build quality | ~255 |

**_Recommendation:_**  
For dual GPU setups, the **Fractal Design Meshify 2** or **Thermaltake Core P8** are excellent choices due to their spacious interiors and superior cooling support, ensuring that multiple GPUs can operate efficiently without overheating.

## **9. Operating System**
> Choose an OS that best supports your ML tools and frameworks. **Ubuntu** is widely used in ML environments due to its compatibility and support for NVIDIA drivers and ML frameworks.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **Operating System** | **Ubuntu 22.04 LTS** | Free, widely supported in ML environments | 0 |
|               | **Windows 11 Pro** | Comprehensive support for various ML tools | ~210 |

**_Recommendation:_**  
**Ubuntu 22.04 LTS** is highly recommended for ML development due to its robust support for NVIDIA drivers, compatibility with popular ML frameworks like TensorFlow and PyTorch, and extensive community support.

## **10. Networking (Optional)**
> For distributed ML workloads or high-speed data transfers, high-speed networking can be beneficial.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **Network Card** | **Intel X550-T2 10GbE** | Dual 10 Gigabit Ethernet ports, PCIe 3.0 | ~450 |
|               | **ASUS XG-C100C 10Gb Ethernet** | PCIe 3.0, reliable performance | ~225 |

**_Recommendation:_**  
If your ML workflows involve significant data transfers over the network, consider adding a **10Gb Ethernet Card** like the **Intel X550-T2** for high-speed connectivity.

## **11. Peripherals (Optional)**
> Quality peripherals can enhance your workflow and overall user experience.

| **Component** | **Recommendation** | **Key Features** | **Price Range (AUD)** |
|---------------|--------------------|-------------------|------------------------|
| **Monitor**   | **Dell UltraSharp U2720Q** | 27-inch 4K, IPS panel, excellent color accuracy | ~900 |
|               | **LG 27GN950-B** | 27-inch 4K, IPS, high refresh rate | ~1,200 |
| **Keyboard**  | **Logitech MX Keys** | Ergonomic, wireless, backlit | ~150 |
|               | **Corsair K95 RGB Platinum** | Mechanical, RGB lighting, programmable keys | ~300 |
| **Mouse**     | **Logitech MX Master 3** | Ergonomic, wireless, multiple programmable buttons | ~150 |
|               | **Razer DeathAdder V2** | High-precision sensor, ergonomic design | ~105 |
| **External Storage** | **Samsung T7 Portable SSD 2TB** | Fast USB 3.2 connectivity, portable | ~375 |
|               | **WD My Passport 4TB** | Large capacity, reliable performance | ~180 |
| **Uninterruptible Power Supply (UPS)** | **APC Back-UPS Pro 1500VA** | Reliable backup power, surge protection | ~375 |
|               | **CyberPower CP1500PFCLCD** | Pure sine wave, LCD display, high capacity | ~300 |

**_Recommendation:_**  
Investing in high-quality monitors like the **Dell UltraSharp U2720Q** and ergonomic peripherals like the **Logitech MX Keys** and **MX Master 3** can significantly enhance your productivity and comfort during long ML development sessions.

## **Complete Component List for an AMD-Based ML Development PC**

| **Component**                   | **Recommendation**                                  | **Price (AUD)** |
|---------------------------------|-----------------------------------------------------|------------------|
| **Motherboard**                 | ASUS PRIME X670-P WIFI CSM DDR5 AM5 ATX             | 450              |
| **CPU**                         | AMD Ryzen 9 7900X                                   | 750              |
| **GPU**                         | NVIDIA GeForce RTX 4090                              | 2,400            |
| **RAM**                         | G.Skill Trident Z5 RGB DDR5 64GB (2x32GB) 6000MHz     | 450              |
| **Primary Storage**             | Samsung 980 PRO 1TB NVMe SSD                         | 150              |
| **Secondary Storage**           | WD Black SN850X 2TB NVMe SSD                         | 300              |
| **CPU Cooler**                  | Corsair iCUE H150i Elite Capellix (AIO Liquid Cooler)| 300              |
| **Power Supply**                | EVGA SuperNOVA 1200 G6 1200W, 80+ Gold Fully Modular  | 450              |
| **Case**                        | Fractal Design Meshify 2                             | 225              |

::: {#5ea46889-9f4f-4ebd-b7e8-eca6581109c8 .cell}
``` {.python .cell-code}
450 + 1050 + 2400 + 450 + 150 + 300 + 300 + 450 + 225 - 2400
```

::: {.cell-output .cell-output-display}
```
3375
```
:::
:::


## **Additional Tips for Building an ML Development PC**

1. **Ensure Compatibility**: Double-check that all components are compatible with each other, especially the motherboard, CPU, and RAM. Use tools like [PCPartPicker](https://pcpartpicker.com/) to verify compatibility and prevent issues during assembly.

2. **Prioritize Cooling**: ML workloads generate significant heat, especially with dual GPUs. Invest in high-quality cooling solutions to maintain system stability and prolong component lifespan.

3. **Cable Management**: A well-organized build not only looks clean but also promotes better airflow. Use modular PSUs and manage cables efficiently within the case.

4. **Future-Proofing**: Select components that offer room for upgrades, such as additional RAM slots, PCIe lanes, and storage options, to accommodate growing ML demands.

5. **Driver and Software Setup**: After assembling your workstation, ensure that you install the latest drivers for your GPU (NVIDIA) and set up ML frameworks like TensorFlow, PyTorch, and others with GPU support.

6. **Backup Solutions**: Implement regular backup strategies to protect your datasets and models. Consider using both local (external SSDs) and cloud-based backup solutions.

7. **Monitor Cooling and Performance**: Use software tools to monitor system temperatures and performance metrics to ensure that your ML tasks are running efficiently without thermal throttling.

## Computer Setup 

- proxmox server
  - Ubuntu
  - Windows
  - NAS
  - 


