# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Hardware_Tools',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/Hardware_Tools',
                'lib_path': 'Hardware_Tools'},
  'syms': {}}
